FROM registry.access.redhat.com/ubi8/openjdk-17:1.20

ENV LANGUAGE='en_US:en'
ENV SERVER_PORT=8088
ENV CORS_ORIGINS=https://api.lions.dev

# Copie du fichier JAR principal
COPY target/btpxpress-client-quarkus-primereact-1.0.0-SNAPSHOT-runner.jar /deployments/app.jar

EXPOSE ${SERVER_PORT}
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Dquarkus.profile=prod -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ENTRYPOINT ["java", "-jar", "/deployments/app.jar"]